version: "2"
run:
  go: "1.14"
  modules-download-mode: readonly
  tests: true
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - errcheck
    - forbidigo
    - gocritic
    - goheader
    - govet
    - ineffassign
    - misspell
    - predeclared
    - staticcheck
    - thelper
    - tparallel
    - unused
  settings:
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forbidigo
        path: examples/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/scylladb/scylla-cdc-go
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
